return {
  "lukas-reineke/indent-blankline.nvim",
  event = { "BufReadPost", "BufNewFile" },
  opts = {
    -- char = "▏",
    char = "│",
    filetype_exclude = {
      "help",
      "alpha",
      "dashboard",
      "neo-tree",
      "Trouble",
      "lazy",
      "mason",
      "notify",
      "toggleterm",
      "lazyterm",
      "help",
      "startify",
      "dashboard",
      "packer",
      "neogitstatus",
      -- "NvimTree",
      "Trouble",
      "text",
    },
    show_trailing_blankline_indent = false,
    show_current_context = true,
    show_current_context_start = true,
  },
}
